---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-liberty-demo
  labels:
    app: open-liberty-demo
spec:
  selector:
    matchLabels:
      app: open-liberty-demo
  template:
    metadata:
      labels:
        app: open-liberty-demo
    spec:
      containers:
      - name: open-liberty-demo
        image: ${APPLICATION_IMAGE}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9080
        - name: https
          containerPort: 9443
        env:
        - name: KEYSTORE_NAME
          valueFrom:
            secretKeyRef:
              name: keystore-secret
              key: keystore.name
        - name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keystore-secret
              key: keystore.password
        - name: POSTGRESQL_SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql.server.name
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql.user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql.password
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: aad-oidc-secret
              key: tenant.id
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: aad-oidc-secret
              key: client.id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: aad-oidc-secret
              key: client.secret
        volumeMounts:
          - name: logs-volume
            mountPath: /logs
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.6.2
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ELASTIC_CLOUD_ID
          valueFrom:
            secretKeyRef:
              name: elastic-cloud-secret
              key: elastic.cloud.id
        - name: ELASTIC_CLOUD_AUTH
          valueFrom:
            secretKeyRef:
              name: elastic-cloud-secret
              key: elastic.cloud.auth
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: logs-volume
          mountPath: /logs
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: open-liberty-demo
spec:
  type: LoadBalancer
  selector:
    app: open-liberty-demo
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: http
  - name: https
    protocol: TCP
    port: 9443
    targetPort: https
