FROM websphere-liberty

COPY --chown=1001:0 src/main/liberty/config /config/
COPY --chown=1001:0 target/liberty/wlp/usr/servers/aad-oidc-integration/bootstrap.properties /config
COPY --chown=1001:0 target/aad-oidc-integration.war /config/apps
